configuration: Release

image: Visual Studio 2017
environment:
  EnableNuGetPackageRestore: true

nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: >-
    nuget update -self
    nuget restore
 
build:
    verbosity: minimal
    publish_wap: true
